ALL =
ALL+=omfG722Recorder_
ALL+=omfG722Player_
##
INCS +=
### plugins
LIBS += -lpluginav
LIBS += -lpluginiofile
LIBS += -lpluginwav
LIBS += -lpluginpcm
LIBS += -lpluging722
LIBS += -lpluginshm
LIBS += -lpluginapistreaming
LIBS += -lpluginshmbase
LIBS += -lpluginbase
### api
LIBS += -lomfapi
LIBS += -lomfapicxx
LIBS += -lomfapistreaming
###
LIBS += -ldl
LIBS += -ldbglinux
###
OBJS +=
###
include ../makefile.tmpl
	