//
// Created by jg.wang on 2019/8/2.
//
#pragma once

namespace omf{
	enum DebugIndex:unsigned{
		DBG_IDX_CHN_0=0,
		DBG_IDX_CHN_1=1,
		DBG_IDX_CHN_2=2,
		DBG_IDX_CHN_3=3,
		DBG_IDX_CHN_4=4,
		DBG_IDX_CHN_5=5,
		DBG_IDX_CHN_6=6,
		DBG_IDX_CHN_7=7,

		DBG_IDX_ERR =8,
		DBG_IDX_LOG =9,
		DBG_IDX_INFO=10,
		DBG_IDX_TEST=11,
		DBG_IDX_NOTE=12,

		DBG_IDX_LV_0=16,
		DBG_IDX_LV_1=17,
		DBG_IDX_LV_2=18,
		DBG_IDX_LV_3=19,
		DBG_IDX_LV_4=20,
		DBG_IDX_LV_5=21,
		DBG_IDX_LV_6=22,
		DBG_IDX_LV_7=23,

		DBG_IDX_RED		=24,
		DBG_IDX_GREEN	=25,
		DBG_IDX_YELLOW	=26,
		DBG_IDX_BLUE	=27,
		DBG_IDX_PINK	=28,
		DBG_IDX_SKY		=29,
	};

	enum DebugSelecter:unsigned{
		DBG_CHN_0=1<<DBG_IDX_CHN_0,
		DBG_CHN_1=1<<DBG_IDX_CHN_1,
		DBG_CHN_2=1<<DBG_IDX_CHN_2,
		DBG_CHN_3=1<<DBG_IDX_CHN_3,
		DBG_CHN_4=1<<DBG_IDX_CHN_4,
		DBG_CHN_5=1<<DBG_IDX_CHN_5,
		DBG_CHN_6=1<<DBG_IDX_CHN_6,
		DBG_CHN_7=1<<DBG_IDX_CHN_7,

		DBG_ERR =1<<DBG_IDX_ERR,
		DBG_LOG =1<<DBG_IDX_LOG,
		DBG_INFO=1<<DBG_IDX_INFO,
		DBG_TEST=1<<DBG_IDX_TEST,
		DBG_NOTE=1<<DBG_IDX_NOTE,

		DBG_LV_0=1<<DBG_IDX_LV_0,
		DBG_LV_1=1<<DBG_IDX_LV_1,
		DBG_LV_2=1<<DBG_IDX_LV_2,
		DBG_LV_3=1<<DBG_IDX_LV_3,
		DBG_LV_4=1<<DBG_IDX_LV_4,
		DBG_LV_5=1<<DBG_IDX_LV_5,
		DBG_LV_6=1<<DBG_IDX_LV_6,
		DBG_LV_7=1<<DBG_IDX_LV_7,

		DBG_RED		=1<<DBG_IDX_RED		,
		DBG_GREEN	=1<<DBG_IDX_GREEN	,
		DBG_YELLOW	=1<<DBG_IDX_YELLOW	,
		DBG_BLUE	=1<<DBG_IDX_BLUE	,
		DBG_PINK	=1<<DBG_IDX_PINK	,
		DBG_SKY		=1<<DBG_IDX_SKY		,
	};
	///
}
