ALL =
ALL+=omfRtmpClient_
ALL+=omfRtmpFromDemuxer_
###
INCS +=
INCS += -I.
INCS += -I${INCS_PATH}
###
LIBS += -lpluginrtmp
LIBS += -lrtmp
###
LIBS += -lpluginav
###
LIBS += -lpluginpcm
##
LIBS += -lpluginaac
###
LIBS += -lplugindev
###
LIBS += -lomfapi
LIBS += -lomfapicxx
LIBS += -lomfapistreaming
LIBS += -lpluginapistreaming
###
LIBS += -lpluginshmbase
LIBS += -lpluginshm
###
LIBS += -lpluginbase
LIBS += -lfwcore
LIBS += -lfwbase
LIBS += -lfwporting
###
LIBS += -lpluginmp4
LIBS += -lpluginwav
###
LIBS += -lomfapistreaming
LIBS += -lpluginio
###
LIBS += -ldl
LIBS += -ldbglinux
###
LIBS += -lssl
LIBS += -lcrypto
#LIBS += -lpolarssl
###
OBJS +=

###
include ../makefile.tmpl