ALL =
ALL+=omfRtmpClient_
ALL+=omfRtmpFromDemuxer_
###
INCS +=
INCS += -I.
INCS += -I${INCS_PATH}
###
LIBS += -lomfapi
LIBS += -lomfapicxx
LIBS += -lomfapistreaming
###
LIBS += -lpluginbase
LIBS += -lpluginapistreaming
LIBS += -lpluginshm
LIBS += -lpluginmp4
LIBS += -lpluginwav
LIBS += -lpluginiofile
LIBS += -lpluginrtmp
LIBS += -lpluginav
LIBS += -lpluginpcm
LIBS += -lpluginaac
LIBS += -lplugindev
###
LIBS += -lz
###
LIBS += -ldl
LIBS += -ldbglinux
###
OBJS +=

###
include ../makefile.tmpl