ALL =
ALL+=omfHumanDetect_
ALL+=omfFaceDetect_
ALL+=omfFaceRecognise_
ALL+=omfNnHumanProcess_
ALL+=omfNnProcess_
ALL+=omfNnIcatosDemo_
###
CFLAGS +=
CXXFLAGS +=
###
INCS += -I.
###
LIBS += -lomfapicxx
###
LIBS += -lpluginshmbase
###
LIBS += -ldl
LIBS += -ldbglinux
###
OBJS +=
###
include ../makefile.tmpl
	