ALL =
ALL+=omfNnProcess_
##
INCS +=
###
LIBS += -lomfapi
LIBS += -lomfapicxx
###
LIBS += -lshm
LIBS += -lpluginshm
LIBS += -lipc
LIBS += -lpluginipc
###
LIBS += -lfwcore
LIBS += -lfwbase
LIBS += -lfwporting
###
LIBS += -ldl
LIBS += -ldbglinux
###
OBJS +=
###
include ../makefile.tmpl
	