ALL =
ALL+=omfWavRecord_
ALL+=omfWavPlayer_
###
CFLAGS +=
CXXFLAGS +=
###
INCS += -I.
### plugins
LIBS += -lpluginiofile
LIBS += -lpluginwav
LIBS += -lpluginav
LIBS += -lpluginpcm
LIBS += -lpluginapistreaming
LIBS += -lpluginshm
LIBS += -lpluginbase
### api
LIBS += -lomfapi
LIBS += -lomfapicxx
LIBS += -lomfapistreaming
###
LIBS += -ldl
LIBS += -ldbglinux
###
OBJS +=
###
include ../makefile.tmpl
	