ALL =
ALL+=omfOggMuxer_
##
INCS +=
###
LIBS += -lpluginiofile
LIBS += -lpluginav
LIBS += -lpluginpcm
LIBS += -lpluginogg
LIBS += -logg
LIBS += -lpluginopus
LIBS += -lopus
###
LIBS += -lomfapi
LIBS += -lomfapicxx
LIBS += -lomfapistreaming
LIBS += -lpluginapistreaming
###
LIBS += -lpluginshmbase
LIBS += -lpluginshm
###
LIBS += -lpluginbase
LIBS += -lfwcore
LIBS += -lfwbase
LIBS += -lfwporting
###
LIBS += -ldl
LIBS += -ldbglinux
###
OBJS +=
###
include ../makefile.tmpl
	