//
// Created by yb.leng on 2020/3/9.
//

#pragma once
typedef enum{
	VOICE_PROMPT_SETUPSTART = 1,
	VOICE_PROMPT_ACCOUNTINVALID,
	VOICE_PROMPT_LOGINFAIL,
	VOICE_PROMPT_LOGINOK,
	VOICE_PROMPT_NETNOTWORK,
	VOICE_PROMPT_NETPARAMCFG,
	VOICE_PROMPT_NETPARAMCFGFAIL,
	VOICE_PROMPT_NETPARAMCFGOK,
	VOICE_PROMPT_NETWORKCONNECTFAIL,
	VOICE_PROMPT_PARAMCFGTIMEOUT,
	VOICE_PROMPT_QRCODESCANTIMEOUT,
	VOICE_PROMPT_QRCODEINVALID,
	VOICE_PROMPT_QRCODEEXPIRED,
	VOICE_PROMPT_SCANNING,
	VOICE_PROMPT_SCANOK,
	VOICE_PROMPT_SERVERTIMEOUT,
	VOICE_PROMPT_WIFICONNECTFAIL,
	VOICE_PROMPT_WIFINOFOUND,
	VOICE_PROMPT_WIFIOK,
	VOICE_PROMPT_WIFISIGNALOK,
	VOICE_PROMPT_WIFISIGNALBAD,
	VOICE_PROMPT_WIFIPWDERROR,
	VOICE_PROMPT_MAX,
}voicePrompts_t;