ALL =
ALL+=omfWifiConnect_
##
INCS +=
INCS += -I.
INCS += -I${INCS_PATH}/mt7682
###
LIBS += -lpluginsmarthomenetlink
###
LIBS += -lomfapi
LIBS += -lomfapicxx
###
LIBS += -lshm
LIBS += -lpluginshm
LIBS += -lipc
LIBS += -lpluginipc
###
LIBS += -lfwcore
LIBS += -lfwbase
LIBS += -lfwporting
###
LIBS += -ldl
LIBS += -ldbglinux
###
OBJS +=
###
include ../makefile.tmpl
	