ALL =
ALL+=omfEventService_
ALL+=omfEventServiceTrigger_
ALL+=omfPreRecord_
###
CFLAGS +=
CXXFLAGS +=
###
INCS += -I.
###
LIBS += -lpluginiofile
LIBS += -lpluginwav
LIBS += -lpluginmp4
LIBS += -lpluginav
LIBS += -lpluginpcm
LIBS += -lpluginprerec
LIBS += -lpluginapistreaming
LIBS += -lpluginshm
LIBS += -lpluginbase
###
LIBS += -lomfapi
LIBS += -lomfapicxx
LIBS += -lomfapistreaming
###
LIBS += -ldl
LIBS += -ldbglinux
###
OBJS +=
###
include ../makefile.tmpl
	