ALL =
ALL+=omfEventService_
###
CFLAGS +=
CXXFLAGS +=
###
INCS += -I.
###
LIBS += -lpluginiofile
LIBS += -lpluginmp4
LIBS += -lpluginav
LIBS += -lpluginprerec
LIBS += -lpluginapistreaming
LIBS += -lpluginshm
LIBS += -lpluginbase
LIBS += -lplugindev
###
LIBS += -lomfapi
LIBS += -lomfapicxx
LIBS += -lomfapistreaming
###
LIBS += -ldl
LIBS += -ldbglinux
###
OBJS +=
###
include ../makefile.tmpl
	