/*
 * icatchtek_mt7682_def.h
 *
 *  Created on: 2019-07-15
 *      Author: j.chen
 */

#ifndef APP_ICATCHTEK_MT7682_DEF_H_
#define APP_ICATCHTEK_MT7682_DEF_H_

typedef struct mt7687_packet_hdr {
    unsigned int type;
    unsigned short length;
    unsigned short seqno;
} __attribute__((packed)) mt7687_packet_hdr_t ;

typedef struct mt7687_packet {
    mt7687_packet_hdr_t header;
    unsigned char* data;
} mt7687_packet_t ;

#define IOT_CMD_OFFSET          (0x00000000)
#define IOT_EVT_OFFSET          (0x00001000)

#define IOT_CMD_GROUP_SHIFT     (8)
#define IOT_CMD_GROUP_ALL       (0x00000F00)
#define IOT_CMD_GROUP_SYSTEM    (0x00000000)    /* ���ݭn�B�z MT7687 return ��� , �L�k wait return */
#define IOT_CMD_GROUP_WIFI      (0x00000100)    /* �ݭn�B�z MT7687 return ��� , �L�k wait return */
#define IOT_CMD_GROUP_SOCKET    (0x00000200)    /* socket �M�� */
#define IOT_CMD_GROUP_REQUEST   (0x00000400)    /* �i�H wait return from MT7687 , �]�i�H�B�z return ��� */
#define IOT_CMD_WAIT_EVENT      (0xFFFFFFFF)

typedef enum
{
    IOT_CMD_SYSTEM_SPI_INITIAL      = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SYSTEM | 0x01) ,
    /* IOT_CMD_SYSTEM_LOW_POWER        = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SYSTEM | 0x02) , */ /* move to IOT_CMD_REQUEST_LOW_POWER */
    IOT_CMD_SYSTEM_HDPC             = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SYSTEM | 0x03) ,
    IOT_CMD_SYSTEM_SPI_SEND_IRQ     = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SYSTEM | 0x04) ,
    IOT_CMD_SYSTEM_UID              = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SYSTEM | 0x05) ,
    IOT_CMD_SYSTEM_WAKEUPPATTERN    = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SYSTEM | 0x06) ,

    #if 0
    IOT_CMD_SYSTEM_CHECK_WAKEUP_INFO = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SYSTEM | 0x07) ,
    IOT_CMD_SYSTEM_ALREADY_WAKEUP_INFO = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SYSTEM | 0x08) ,
    IOT_CMD_SYSTEM_NO_WAKEUP_INFO   = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SYSTEM | 0x09) ,
    #endif

    IOT_CMD_SYSTEM_EVENT_NOTIFY     = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SYSTEM | 0x0B),
    IOT_CMD_SYSTEM_UPDATE_DONE      = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SYSTEM | 0x0C),
    IOT_CMD_SYSTEM_PIR_SEN_SET      = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SYSTEM | 0x0D),
    IOT_CMD_SYSTEM_PIR_REC_ENABLE   = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SYSTEM | 0x0E),
    IOT_CMD_SYSTEM_PIR_MSG_ENABLE   = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SYSTEM | 0x0F),
    IOT_CMD_SYSTEM_PIR_ENABLE       = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SYSTEM | 0x10),
    IOT_CMD_SYSTEM_RESET			= (IOT_CMD_OFFSET | IOT_CMD_GROUP_SYSTEM | 0x11),
    IOT_CMD_SYSTEM_SD_STATUS        = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SYSTEM | 0x12),
    IOT_CMD_SYSTEM_SERI_WRITE_DONE  = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SYSTEM | 0x13),
    IOT_CMD_SYSTEM_PIR_INT_SET      = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SYSTEM | 0x14),
    IOT_CMD_SYSTEM_BATTERY_SET      = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SYSTEM | 0x15),
    IOT_CMD_SYSTEM_SERVICE_CTRL     = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SYSTEM | 0x16),
    IOT_CMD_SYSTEM_PIR_STAT_SET     = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SYSTEM | 0x17),
    IOT_CMD_SYSTEM_SPI_BUS_TEST2    = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SYSTEM | 0x18),

    IOT_CMD_WIFI_AP_INITIAL         = (IOT_CMD_OFFSET | IOT_CMD_GROUP_WIFI   | 0x01) ,
    IOT_CMD_WIFI_AP_CONNECTING      = (IOT_CMD_OFFSET | IOT_CMD_GROUP_WIFI   | 0x02) ,
    IOT_CMD_WIFI_AP_CONNECTION      = (IOT_CMD_OFFSET | IOT_CMD_GROUP_WIFI   | 0x03) ,
    IOT_CMD_WIFI_AP_CONNECTED       = (IOT_CMD_OFFSET | IOT_CMD_GROUP_WIFI   | 0x04) ,
    IOT_CMD_WIFI_AP_DISCONNECTION   = (IOT_CMD_OFFSET | IOT_CMD_GROUP_WIFI   | 0x05) ,
    IOT_CMD_WIFI_STA_INITIAL        = (IOT_CMD_OFFSET | IOT_CMD_GROUP_WIFI   | 0x06) ,
    IOT_CMD_WIFI_STA_CONNECTION     = (IOT_CMD_OFFSET | IOT_CMD_GROUP_WIFI   | 0x07) ,
    IOT_CMD_WIFI_STA_DISCONNECTED   = (IOT_CMD_OFFSET | IOT_CMD_GROUP_WIFI   | 0x08) ,
    IOT_CMD_WIFI_STA_DISCONNECTION  = (IOT_CMD_OFFSET | IOT_CMD_GROUP_WIFI   | 0x09) ,
    IOT_CMD_WIFI_GET_IPCONFIG       = (IOT_CMD_OFFSET | IOT_CMD_GROUP_WIFI   | 0x0A) ,
    IOT_CMD_WIFI_PING               = (IOT_CMD_OFFSET | IOT_CMD_GROUP_WIFI   | 0x0B) ,
    IOT_CMD_WIFI_MODE_GET           = (IOT_CMD_OFFSET | IOT_CMD_GROUP_WIFI   | 0x0C) ,
    IOT_CMD_WIFI_AP_SCAN_START      = (IOT_CMD_OFFSET | IOT_CMD_GROUP_WIFI   | 0x0D) ,
    IOT_CMD_WIFI_AP_SCAN_STOP       = (IOT_CMD_OFFSET | IOT_CMD_GROUP_WIFI   | 0x0E) ,
    IOT_CMD_WIFI_PUSH_ACTION        = (IOT_CMD_OFFSET | IOT_CMD_GROUP_WIFI   | 0x0F) ,
    IOT_CMD_WIFI_STA_IP_READY       = (IOT_CMD_OFFSET | IOT_CMD_GROUP_WIFI   | 0x11) ,
    /* IOT_CMD_WIFI_SPI_FOTA			= (IOT_CMD_OFFSET | IOT_CMD_GROUP_WIFI | 0x12), */ /* move to IOT_CMD_REQUEST_SPI_FOTA */
    IOT_CMD_WIFI_GET_CURRENT_TIME   = (IOT_CMD_OFFSET | IOT_CMD_GROUP_WIFI | 0x13),
    IOT_CMD_WIFI_GET_WIFI_RSSI      = (IOT_CMD_OFFSET | IOT_CMD_GROUP_WIFI | 0x14),

    #if 0 /* not support */
    IOT_CMD_WIFI_GET_BATTERY        = (IOT_CMD_OFFSET | IOT_CMD_GROUP_WIFI | 0X15),
    #else
    IOT_CMD_WIFI_GET_LVD_STATUS     = (IOT_CMD_OFFSET | IOT_CMD_GROUP_WIFI | 0X15),
    #endif

    IOT_CMD_WIFI_PIR_SERI_WRITE     = (IOT_CMD_OFFSET | IOT_CMD_GROUP_WIFI | 0x16),
    IOT_CMD_WIFI_SMTCON_INITIAL     = (IOT_CMD_OFFSET | IOT_CMD_GROUP_WIFI | 0x31) ,
    IOT_CMD_WIFI_SMTCON_START       = (IOT_CMD_OFFSET | IOT_CMD_GROUP_WIFI | 0x32) ,
    IOT_CMD_WIFI_SMTCON_CONNECTED   = (IOT_CMD_OFFSET | IOT_CMD_GROUP_WIFI | 0x33) ,
    IOT_CMD_WIFI_SMTCON_TIMEOUT     = (IOT_CMD_OFFSET | IOT_CMD_GROUP_WIFI | 0x34) ,
    IOT_CMD_WIFI_SMTCON_END         = (IOT_CMD_OFFSET | IOT_CMD_GROUP_WIFI | 0x35) ,
    IOT_CMD_WIFI_SMTCON_APMODE      = (IOT_CMD_OFFSET | IOT_CMD_GROUP_WIFI | 0x36) ,
    IOT_CMD_WIFI_GET_ADC_RESULT     = (IOT_CMD_OFFSET | IOT_CMD_GROUP_WIFI | 0x37) ,
    IOT_CMD_WIFI_SHUTDOWN           = (IOT_CMD_OFFSET | IOT_CMD_GROUP_WIFI | 0x38) ,
    IOT_CMD_WIFI_SYSTEM_OFF         = (IOT_CMD_OFFSET | IOT_CMD_GROUP_WIFI | 0x39) ,
    IOT_CMD_WIFI_BAT_LEVEL_CHANGE   = (IOT_CMD_OFFSET | IOT_CMD_GROUP_WIFI | 0x3A) ,

    IOT_CMD_SOCKET_ADD              = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SOCKET | 0x01) ,
    IOT_CMD_SOCKET_BIND             = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SOCKET | 0x02) ,
    IOT_CMD_SOCKET_SEND             = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SOCKET | 0x03) ,
    IOT_CMD_SOCKET_ACCEPT           = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SOCKET | 0x04) ,
    IOT_CMD_SOCKET_LISTEN           = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SOCKET | 0x05) ,
    IOT_CMD_SOCKET_CONNECT          = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SOCKET | 0x06) ,
    IOT_CMD_SOCKET_SELECT           = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SOCKET | 0x07) ,
    IOT_CMD_SOCKET_SETOPT           = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SOCKET | 0x08) ,
    IOT_CMD_SOCKET_GETOPT           = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SOCKET | 0x09) ,
    IOT_CMD_SOCKET_CLOSE            = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SOCKET | 0x0A) ,
    IOT_CMD_SOCKET_RECVFROM         = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SOCKET | 0x0B) ,
    IOT_CMD_SOCKET_SENDTO           = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SOCKET | 0x0C) ,
    IOT_CMD_SOCKET_FCNTL            = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SOCKET | 0x0D) ,
    IOT_CMD_SOCKET_GETADDRNAME      = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SOCKET | 0x0E) ,
    IOT_CMD_SOCKET_IOCTL            = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SOCKET | 0x0F) ,
    IOT_CMD_SOCKET_SHUTDOWN         = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SOCKET | 0x10) ,
    IOT_CMD_SOCKET_GETHOSTBTNAME    = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SOCKET | 0x11) ,
    IOT_CMD_SOCKET_SENDTO_MORE      = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SOCKET | 0x12) ,
    IOT_CMD_SOCKET_RECVAUTO         = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SOCKET | 0x13) ,
    IOT_CMD_SOCKET_UPDATE           = (IOT_CMD_OFFSET | IOT_CMD_GROUP_SOCKET | 0x14) ,

    IOT_CMD_REQUEST_SPI_BUS_TEST0    = (IOT_CMD_OFFSET | IOT_CMD_GROUP_REQUEST | 0x01) ,
    IOT_CMD_REQUEST_SPI_BUS_TEST1    = (IOT_CMD_OFFSET | IOT_CMD_GROUP_REQUEST | 0x02) ,
    IOT_CMD_REQUEST_GET_VERSION      = (IOT_CMD_OFFSET | IOT_CMD_GROUP_REQUEST | 0x03) ,
    IOT_CMD_REQUEST_LOW_POWER        = (IOT_CMD_OFFSET | IOT_CMD_GROUP_REQUEST | 0x04) ,
    IOT_CMD_REQUEST_SPI_FOTA         = (IOT_CMD_OFFSET | IOT_CMD_GROUP_REQUEST | 0x05) ,
    IOT_CMD_REQUEST_PUSH_MSG         = (IOT_CMD_OFFSET | IOT_CMD_GROUP_REQUEST | 0x06) ,
    IOT_CMD_REQUEST_GET_MACADDR      = (IOT_CMD_OFFSET | IOT_CMD_GROUP_REQUEST | 0x07) ,
    IOT_CMD_REQUEST_PUSH_FILENAME    = (IOT_CMD_OFFSET | IOT_CMD_GROUP_REQUEST | 0x08) ,
    IOT_CMD_REQUEST_WAKEUP_INFO      = (IOT_CMD_OFFSET | IOT_CMD_GROUP_REQUEST | 0x09) ,
    IOT_CMD_REQUEST_FOTALOADER_UPD   = (IOT_CMD_OFFSET | IOT_CMD_GROUP_REQUEST | 0x0A) ,
    IOT_CMD_REQUEST_PING             = (IOT_CMD_OFFSET | IOT_CMD_GROUP_REQUEST | 0x0B) ,

    IOT_CMD_REQUEST_APMODE_STOP      = (IOT_CMD_OFFSET | IOT_CMD_GROUP_REQUEST | 0x31) ,
    IOT_CMD_REQUEST_STAMODE_STOP     = (IOT_CMD_OFFSET | IOT_CMD_GROUP_REQUEST | 0x32) ,
    IOT_CMD_REQUEST_GET_WAKEUP_EVENT = (IOT_CMD_OFFSET | IOT_CMD_GROUP_REQUEST | 0x33) ,
    IOT_CMD_REQUEST_GET_ADC_ACTION   = (IOT_CMD_OFFSET | IOT_CMD_GROUP_REQUEST | 0x34) ,
    IOT_CMD_REQUEST_WIFI_STATISTICS  = (IOT_CMD_OFFSET | IOT_CMD_GROUP_REQUEST | 0x3F) ,
    /* 0xF0 ~ 0xFF reserved for custom */
    IOT_CMD_REQUEST_CUSTOM_CMD       = (IOT_CMD_OFFSET | IOT_CMD_GROUP_REQUEST | 0xF0) ,
}IOT_SPI_CMD_TYPE;


typedef enum
{
    IOT_EVT_WIFI_ERROR              = (IOT_EVT_OFFSET | IOT_CMD_GROUP_WIFI | 0x10 ) ,
    IOT_EVT_SYSTEM_SPI_INITIAL      = (IOT_EVT_OFFSET | IOT_CMD_SYSTEM_SPI_INITIAL ) ,
    /* IOT_EVT_SYSTEM_LOW_POWER        = (IOT_EVT_OFFSET | IOT_CMD_SYSTEM_LOW_POWER ) , */
    IOT_EVT_SYSTEM_HDPC             = (IOT_EVT_OFFSET | IOT_CMD_SYSTEM_HDPC ) ,
    IOT_EVT_SYSTEM_SPI_SEND_IRQ     = (IOT_EVT_OFFSET | IOT_CMD_SYSTEM_SPI_SEND_IRQ ) ,
    IOT_EVT_SYSTEM_UID              = (IOT_EVT_OFFSET | IOT_CMD_SYSTEM_UID ) ,
    IOT_EVT_SYSTEM_WAKEUPPATTERN    = (IOT_EVT_OFFSET | IOT_CMD_SYSTEM_WAKEUPPATTERN ) ,

    #if 0
    IOT_EVT_SYSTEM_CHECK_WAKEUP_INFO = (IOT_EVT_OFFSET | IOT_CMD_SYSTEM_CHECK_WAKEUP_INFO ) ,
    IOT_EVT_SYSTEM_ALREADY_WAKEUP_INFO = (IOT_EVT_OFFSET | IOT_CMD_SYSTEM_ALREADY_WAKEUP_INFO ) ,
    IOT_EVT_SYSTEM_NO_WAKEUP_INFO   = (IOT_EVT_OFFSET | IOT_CMD_SYSTEM_NO_WAKEUP_INFO ) ,
    #endif

    IOT_EVT_SYSTEM_EVENT_NOTIFY     = (IOT_EVT_OFFSET | IOT_CMD_SYSTEM_EVENT_NOTIFY),
    IOT_EVT_SYSTEM_UPDATE_DONE      = (IOT_EVT_OFFSET | IOT_CMD_SYSTEM_UPDATE_DONE),
    IOT_EVT_SYSTEM_PIR_SET          = (IOT_EVT_OFFSET | IOT_CMD_SYSTEM_PIR_SEN_SET),
    IOT_EVT_SYSTEM_PIR_REC_ENABLE   = (IOT_EVT_OFFSET | IOT_CMD_SYSTEM_PIR_REC_ENABLE),
    IOT_EVT_SYSTEM_PIR_MSG_ENABLE   = (IOT_EVT_OFFSET | IOT_CMD_SYSTEM_PIR_MSG_ENABLE),
    IOT_EVT_SYSTEM_PIR_ENABLE       = (IOT_EVT_OFFSET | IOT_CMD_SYSTEM_PIR_ENABLE),
    IOT_EVT_SYSTEM_RESET			= (IOT_EVT_OFFSET | IOT_CMD_SYSTEM_RESET),
    IOT_EVT_SYSTEM_SD_STATUS	    = (IOT_EVT_OFFSET | IOT_CMD_SYSTEM_SD_STATUS),
    IOT_EVT_SYSTEM_SERI_WRITE_DONE  = (IOT_EVT_OFFSET | IOT_CMD_SYSTEM_SERI_WRITE_DONE),
    IOT_EVT_SYSTEM_PIR_INT_SET      = (IOT_EVT_OFFSET | IOT_CMD_SYSTEM_PIR_INT_SET),
    IOT_EVT_SYSTEM_BATTERY_SET      = (IOT_EVT_OFFSET | IOT_CMD_SYSTEM_BATTERY_SET),
    IOT_EVT_SYSTEM_SERVICE_CTRL     = (IOT_EVT_OFFSET | IOT_CMD_SYSTEM_SERVICE_CTRL),
    IOT_EVT_SYSTEM_PIR_STAT_SET     = (IOT_EVT_OFFSET | IOT_CMD_SYSTEM_PIR_STAT_SET),
    IOT_EVT_SYSTEM_SPI_BUS_TEST2    = (IOT_EVT_OFFSET | IOT_CMD_SYSTEM_SPI_BUS_TEST2),

    IOT_EVT_WIFI_AP_INITIAL         = (IOT_EVT_OFFSET | IOT_CMD_WIFI_AP_INITIAL ) ,
    IOT_EVT_WIFI_AP_CONNECTING      = (IOT_EVT_OFFSET | IOT_CMD_WIFI_AP_CONNECTING ) ,
    IOT_EVT_WIFI_AP_CONNECTION      = (IOT_EVT_OFFSET | IOT_CMD_WIFI_AP_CONNECTION ) ,
    IOT_EVT_WIFI_AP_CONNECTED       = (IOT_EVT_OFFSET | IOT_CMD_WIFI_AP_CONNECTED ) ,
    IOT_EVT_WIFI_AP_DISCONNECTION   = (IOT_EVT_OFFSET | IOT_CMD_WIFI_AP_DISCONNECTION ) ,
    IOT_EVT_WIFI_STA_INITIAL        = (IOT_EVT_OFFSET | IOT_CMD_WIFI_STA_INITIAL ) ,
    IOT_EVT_WIFI_STA_CONNECTION     = (IOT_EVT_OFFSET | IOT_CMD_WIFI_STA_CONNECTION ) ,
    IOT_EVT_WIFI_STA_DISCONNECTED   = (IOT_EVT_OFFSET | IOT_CMD_WIFI_STA_DISCONNECTED ) ,
    IOT_EVT_WIFI_STA_DISCONNECTION  = (IOT_EVT_OFFSET | IOT_CMD_WIFI_STA_DISCONNECTION ) ,
    IOT_EVT_WIFI_GET_IPCONFIG       = (IOT_EVT_OFFSET | IOT_CMD_WIFI_GET_IPCONFIG ) ,
    IOT_EVT_WIFI_PING               = (IOT_EVT_OFFSET | IOT_CMD_WIFI_PING ) ,
    IOT_EVT_WIFI_MODE_GET           = (IOT_EVT_OFFSET | IOT_CMD_WIFI_MODE_GET ) ,
    IOT_EVT_WIFI_AP_SCAN_START      = (IOT_EVT_OFFSET | IOT_CMD_WIFI_AP_SCAN_START ) ,
    IOT_EVT_WIFI_AP_SCAN_STOP       = (IOT_EVT_OFFSET | IOT_CMD_WIFI_AP_SCAN_STOP ) ,
    IOT_EVT_WIFI_PUSH_ACTION        = (IOT_EVT_OFFSET | IOT_CMD_WIFI_PUSH_ACTION ) ,
    IOT_EVT_WIFI_STA_IP_READY       = (IOT_EVT_OFFSET | IOT_CMD_WIFI_STA_IP_READY ) ,
    /* IOT_EVT_WIFI_SPI_FOTA           = (IOT_EVT_OFFSET | IOT_CMD_WIFI_SPI_FOTA), */
    IOT_EVT_WIFI_GET_CURRENT_TIME   = (IOT_EVT_OFFSET | IOT_CMD_WIFI_GET_CURRENT_TIME),
    IOT_EVT_WIFI_GET_WIFI_RSSI      = (IOT_EVT_OFFSET | IOT_CMD_WIFI_GET_WIFI_RSSI),

    #if 0 /* not support */
    IOT_EVT_WIFI_GET_BATTERY        = (IOT_EVT_OFFSET | IOT_CMD_WIFI_GET_BATTERY),
    #else
    IOT_EVT_WIFI_GET_LVD_STATUS     = (IOT_EVT_OFFSET | IOT_CMD_WIFI_GET_LVD_STATUS),
    #endif

    IOT_EVT_WIFI_PIR_SERI_WRITE     = (IOT_CMD_OFFSET | IOT_CMD_WIFI_PIR_SERI_WRITE),
    IOT_EVT_WIFI_SMTCON_INITIAL     = (IOT_EVT_OFFSET | IOT_CMD_WIFI_SMTCON_INITIAL ) ,
    IOT_EVT_WIFI_SMTCON_START       = (IOT_EVT_OFFSET | IOT_CMD_WIFI_SMTCON_START ) ,
    IOT_EVT_WIFI_SMTCON_CONNECTED   = (IOT_EVT_OFFSET | IOT_CMD_WIFI_SMTCON_CONNECTED ) ,
    IOT_EVT_WIFI_SMTCON_TIMEOUT     = (IOT_EVT_OFFSET | IOT_CMD_WIFI_SMTCON_TIMEOUT ) ,
    IOT_EVT_WIFI_SMTCON_END         = (IOT_EVT_OFFSET | IOT_CMD_WIFI_SMTCON_END ) ,
    IOT_EVT_WIFI_SMTCON_APMODE      = (IOT_EVT_OFFSET | IOT_CMD_WIFI_SMTCON_APMODE ) ,
    IOT_EVT_WIFI_GET_ADC_RESULT     = (IOT_EVT_OFFSET | IOT_CMD_WIFI_GET_ADC_RESULT ) ,
    IOT_EVT_WIFI_SHUTDOWN           = (IOT_EVT_OFFSET | IOT_CMD_WIFI_SHUTDOWN ) ,
    IOT_EVT_WIFI_SYSTEM_OFF         = (IOT_EVT_OFFSET | IOT_CMD_WIFI_SYSTEM_OFF ) ,
    IOT_EVT_WIFI_BAT_LEVEL_CHANGE   = (IOT_EVT_OFFSET | IOT_CMD_WIFI_BAT_LEVEL_CHANGE ) ,

    IOT_EVT_SOCKET_ADD              = (IOT_EVT_OFFSET | IOT_CMD_SOCKET_ADD ) ,
    IOT_EVT_SOCKET_BIND             = (IOT_EVT_OFFSET | IOT_CMD_SOCKET_BIND ) ,
    IOT_EVT_SOCKET_SEND             = (IOT_EVT_OFFSET | IOT_CMD_SOCKET_SEND ) ,
    IOT_EVT_SOCKET_ACCEPT           = (IOT_EVT_OFFSET | IOT_CMD_SOCKET_ACCEPT ) ,
    IOT_EVT_SOCKET_LISTEN           = (IOT_EVT_OFFSET | IOT_CMD_SOCKET_LISTEN ) ,
    IOT_EVT_SOCKET_CONNECT          = (IOT_EVT_OFFSET | IOT_CMD_SOCKET_CONNECT ) ,
    IOT_EVT_SOCKET_SELECT           = (IOT_EVT_OFFSET | IOT_CMD_SOCKET_SELECT ) ,
    IOT_EVT_SOCKET_SETOPT           = (IOT_EVT_OFFSET | IOT_CMD_SOCKET_SETOPT ) ,
    IOT_EVT_SOCKET_GETOPT           = (IOT_EVT_OFFSET | IOT_CMD_SOCKET_GETOPT ) ,
    IOT_EVT_SOCKET_CLOSE            = (IOT_EVT_OFFSET | IOT_CMD_SOCKET_CLOSE ) ,
    IOT_EVT_SOCKET_RECVFROM         = (IOT_EVT_OFFSET | IOT_CMD_SOCKET_RECVFROM ) ,
    IOT_EVT_SOCKET_SENDTO           = (IOT_EVT_OFFSET | IOT_CMD_SOCKET_SENDTO ) ,
    IOT_EVT_SOCKET_FCNTL            = (IOT_EVT_OFFSET | IOT_CMD_SOCKET_FCNTL ) ,
    IOT_EVT_SOCKET_GETADDRNAME      = (IOT_EVT_OFFSET | IOT_CMD_SOCKET_GETADDRNAME ) ,
    IOT_EVT_SOCKET_IOCTL            = (IOT_EVT_OFFSET | IOT_CMD_SOCKET_IOCTL ) ,
    IOT_EVT_SOCKET_SHUTDOWN         = (IOT_EVT_OFFSET | IOT_CMD_SOCKET_SHUTDOWN ) ,
    IOT_EVT_SOCKET_GETHOSTBTNAME    = (IOT_EVT_OFFSET | IOT_CMD_SOCKET_GETHOSTBTNAME ) ,
    IOT_EVT_SOCKET_SENDTO_MORE      = (IOT_EVT_OFFSET | IOT_CMD_SOCKET_SENDTO_MORE ) ,
    IOT_EVT_SOCKET_RECVAUTO         = (IOT_EVT_OFFSET | IOT_CMD_SOCKET_RECVAUTO ) ,
    IOT_EVT_SOCKET_UPDATE           = (IOT_EVT_OFFSET | IOT_CMD_SOCKET_UPDATE ) ,

    IOT_EVT_REQUEST_SPI_BUS_TEST0    = (IOT_EVT_OFFSET | IOT_CMD_REQUEST_SPI_BUS_TEST0 ) ,
    IOT_EVT_REQUEST_SPI_BUS_TEST1    = (IOT_EVT_OFFSET | IOT_CMD_REQUEST_SPI_BUS_TEST1 ) ,
    IOT_EVT_REQUEST_GET_VERSION      = (IOT_EVT_OFFSET | IOT_CMD_REQUEST_GET_VERSION ) ,
    IOT_EVT_REQUEST_LOW_POWER        = (IOT_EVT_OFFSET | IOT_CMD_REQUEST_LOW_POWER ) ,
    IOT_EVT_REQUEST_SPI_FOTA         = (IOT_EVT_OFFSET | IOT_CMD_REQUEST_SPI_FOTA ),
    IOT_EVT_REQUEST_PUSH_MSG         = (IOT_EVT_OFFSET | IOT_CMD_REQUEST_PUSH_MSG ),
    IOT_EVT_REQUEST_GET_MACADDR      = (IOT_EVT_OFFSET | IOT_CMD_REQUEST_GET_MACADDR) ,
    IOT_EVT_REQUEST_PUSH_FILENAME    = (IOT_EVT_OFFSET | IOT_CMD_REQUEST_PUSH_FILENAME) ,
    IOT_EVT_REQUEST_WAKEUP_INFO      = (IOT_EVT_OFFSET | IOT_CMD_REQUEST_WAKEUP_INFO) ,
    IOT_EVT_REQUEST_FOTALOADER_UPD   = (IOT_EVT_OFFSET | IOT_CMD_REQUEST_FOTALOADER_UPD ),
    IOT_EVT_REQUEST_PING             = (IOT_EVT_OFFSET | IOT_CMD_REQUEST_PING ),

    IOT_EVT_REQUEST_APMODE_STOP      = (IOT_EVT_OFFSET | IOT_CMD_REQUEST_APMODE_STOP ) ,
    IOT_EVT_REQUEST_STAMODE_STOP     = (IOT_EVT_OFFSET | IOT_CMD_REQUEST_STAMODE_STOP ) ,
    IOT_EVT_REQUEST_GET_WAKEUP_EVENT = (IOT_EVT_OFFSET | IOT_CMD_REQUEST_GET_WAKEUP_EVENT ) ,
    IOT_EVT_REQUEST_GET_ADC_ACTION   = (IOT_EVT_OFFSET | IOT_CMD_REQUEST_GET_ADC_ACTION ) ,
    IOT_EVT_REQUEST_WIFI_STATISTICS  = (IOT_EVT_OFFSET | IOT_CMD_REQUEST_WIFI_STATISTICS ) ,
    /* 0xF0 ~ 0xFF reserved for custom */
    IOT_EVT_REQUEST_CUSTOM_CMD       = (IOT_EVT_OFFSET | IOT_CMD_REQUEST_CUSTOM_CMD) ,
}IOT_SPI_EVT_TYPE;

#endif /* APP_ICATCHTEK_MT7682_DEF_H_ */
