ALL+=
Targets?=$(ALL)
###
all:$(Targets)
###

ifeq ($(GCC7.3), 1)
    PREFIX_= /opt/openwrt_toolchain/arm-openwrt-icatchtek-bsp4-glibc/bin/arm-openwrt-linux-gnueabi-
else
    PREFIX_= /opt/openwrt_toolchain/arm-openwrt-icatchtek-glibc/bin/arm-openwrt-linux-
endif
PREFIX?=$(PREFIX_)
LIBS_PATH ?= ../../lib
INCS_PATH ?= ../../include
OUT_PATH ?= ./out
###
GCC ?= ${PREFIX}gcc
GXX ?= ${PREFIX}g++
GSTRIP ?= ${PREFIX}strip
###
CFLAGS += -Wno-error=pointer-sign -Wno-error=char-subscripts -Wno-error=unused-but-set-variable -Wno-error=unused-function
CFLAGS += -mcpu=cortex-a7 -mabi=aapcs -mfloat-abi=hard -mlittle-endian -mno-unaligned-access
CFLAGS += -flax-vector-conversions -mfpu=neon-vfpv4
CFLAGS += -rdynamic -fPIC
CXXFLAGS += ${CFLAGS} -std=c++11 -Wall -g -O2 -fpermissive -fexceptions -Woverloaded-virtual -Wreturn-type -pthread

###
INCS += -I.
INCS += -I${INCS_PATH}/
INCS += -I${INCS_PATH}/core
INCS += -I${INCS_PATH}/streaming
INCS += -I${INCS_PATH}/streaming/common
##
LIBS +=
###
OBJS +=
###
OBJS_+=
###
%.o:%.cpp
	@echo "compile cxx files..."
	$(GXX) $(INCS) $(CXXFLAGS) -c $^ -o $@

%.o:%.cc
	@echo "compile cxx files..."
	$(GXX) $(INCS) $(CXXFLAGS) -c $^ -o $@

%.o:%.c
	@echo "compile c files...."
	$(GCC) $(INCS) $(CFLAGS) -c $^ -o $@

%_:_%.o ${OBJS_}
	@echo $@
	$(GXX) $(INCS) $(CXXFLAGS) $^ -L${LIBS_PATH} $(LIBS) $(LDFLAGS) -o $@

%.so:$(OBJS)
	@echo $@
	$(GXX) $(INCS) $(CXXFLAGS) $^ -shared -o $@

%.a:$(OBJS)
	@echo $@
	$(GXX) $(INCS) $(CXXFLAGS) $^ -o $@

###	
clean:
	@echo "Removing linked and compiled files......"
	rm -rf $(Targets) *.o ./out

###
install:all
	@mkdir -p $(OUT_PATH)
	@for tmp in $(Targets); \
	do \
		mv $$tmp $(OUT_PATH); \
	done

.PHONY : clean install

printAll:
	@echo $(ALL)
