ALL =
ALL+=omfMsgSite_
ALL+=omfMsgSite0_
ALL+=omfMemPool_
###
CFLAGS +=
CXXFLAGS +=
###
INCS += -I.
###
LIBS += -lomfapi
LIBS += -lomfapicxx
#LIBS += -lomfapistreaming
#LIBS += -lpluginapistreaming
###
LIBS += -lshm
LIBS += -lpluginshm
LIBS += -lipc
LIBS += -lpluginipc
###
LIBS += -lpluginbase
LIBS += -lfwcore
LIBS += -lfwbase
LIBS += -lfwporting
###
LIBS += -ldl
LIBS += -ldbglinux
###
OBJS +=
###
OBJS +=
###
include ../makefile.tmpl
	