ALL =
ALL+=omfMsgReceive_
ALL+=omfMsgReceive0_
ALL+=omfMsgSend_
ALL+=omfMsgSend0_
###
CFLAGS +=
CXXFLAGS +=
###
INCS += -I.
###
LIBS += -lomfapicxx
LIBS += -lomfapi
###
LIBS += -ldl
LIBS += -ldbglinux
###
OBJS +=
###
include ../makefile.tmpl
	