ALL =
ALL+=omfPcmSrc_
ALL+=omfAacSrc_
ALL+=omfYuvSrc_
ALL+=omfH264Src_
ALL+=omfJpegSrc_
ALL+=omfSpeaker_
ALL+=omfMicrophone_
ALL+=omfPcmPlay_
ALL+=omfAudSrc_
ALL+=omfAudPlay_
###
CFLAGS +=
CXXFLAGS +=
###
INCS += -I.
###
LIBS += -lpluginaac
LIBS += -lpluging711
LIBS += -lpluging722
LIBS += -lpluginpcm
LIBS += -lplugindev
###
LIBS += -lpluginiofile
LIBS += -lpluginav
###
LIBS += -lomfapi
LIBS += -lomfapicxx
LIBS += -lomfapistreaming
LIBS += -lpluginapistreaming
###
LIBS += -lpluginshmbase
LIBS += -lpluginshm
###
LIBS += -lpluginbase
LIBS += -lfwcore
LIBS += -lfwbase
LIBS += -lfwporting
###
LIBS += -ldl
LIBS += -ldbglinux
###
OBJS +=
###
include ../makefile.tmpl
	