ALL =
ALL+=omfRecorder_
ALL+=omfAudioRecorder_
ALL+=omfAudioPlayer_
ALL+=omfMultiStream_
ALL+=omfNnRecorder_
##
INCS +=
###
LIBS += -lplugindev
LIBS += -lpluging722
LIBS += -lpluginiofile
LIBS += -lpluginwav
LIBS += -lpluginmp4
LIBS += -lpluginav
LIBS += -lpluginpcm
LIBS += -lpluginapistreaming
LIBS += -lpluginshm
LIBS += -lpluginbase
###
LIBS += -lomfapi
LIBS += -lomfapicxx
LIBS += -lomfapistreaming
###
LIBS += -ldl
LIBS += -ldbglinux
###
OBJS +=
###
include ../makefile.tmpl
	