ALL =
ALL+=omfStampService_
ALL+=omfStampSet_
###
CFLAGS +=
CXXFLAGS +=
###
INCS += -I.
###
LIBS += -lpluginiofile
###
LIBS += -lomfapi
LIBS += -lomfapicxx
###
LIBS += -lpluginshmbase
###
LIBS += -lfwbase
LIBS += -lfwporting
###
LIBS += -ldl
LIBS += -ldbglinux
###
OBJS +=
###
include ../makefile.tmpl

	