ALL =
ALL+=omfRtmpClient_
###
CFLAGS +=
CXXFLAGS +=
###
LIBS += -lpluginrtmp
LIBS += -lrtmp
###
LIBS += -lpluginav
###
LIBS += -lomfapi
LIBS += -lomfapicxx
LIBS += -lomfapistreaming
LIBS += -lpluginapistreaming
###
LIBS += -lshm
LIBS += -lpluginshm
LIBS += -lipc
LIBS += -lpluginipc
###
LIBS += -lpluginbase
LIBS += -lfwcore
LIBS += -lfwbase
LIBS += -lfwporting
###
LIBS += -ldl
LIBS += -ldbglinux
###
INCS +=
###
include ../makefile.tmpl

