ALL =
ALL+=omfG711Recorder_
ALL+=omfG711Player_
##
INCS +=
###
LIBS += -lpluginiofile
LIBS += -lpluginwav
LIBS += -lpluginmp4
LIBS += -lpluginav
LIBS += -lpluginpcm
LIBS += -lpluging711
###
LIBS += -lomfapi
LIBS += -lomfapicxx
LIBS += -lomfapistreaming
LIBS += -lpluginapistreaming
###
LIBS += -lshm
LIBS += -lpluginshm
LIBS += -lipc
LIBS += -lpluginipc
###
LIBS += -lpluginbase
LIBS += -lfwcore
LIBS += -lfwbase
LIBS += -lfwporting
###
LIBS += -ldl
LIBS += -ldbglinux
###
OBJS +=
###
include ../makefile.tmpl
	