ALL =
ALL+=omfRtspServer_
###
CFLAGS +=
CXXFLAGS +=
###
LIBS += -lpluginrtsp4
###
LIBS += -lpluginpcm
LIBS += -lpluginav
LIBS += -lplugindev
###
LIBS += -lomfapi
LIBS += -lomfapicxx
LIBS += -lomfapistreaming
LIBS += -lpluginapistreaming
###
LIBS += -lpluginshmbase
LIBS += -lpluginshm
###
LIBS += -lpluginbase
LIBS += -lfwcore
LIBS += -lfwbase
LIBS += -lfwporting
###
LIBS += -ldl
LIBS += -ldbglinux
###
INCS +=
###
include ../makefile.tmpl

