ALL =
ALL+=omfRtspServer_
###
CFLAGS +=
CXXFLAGS +=
###
LIBS += -lliveMedia
LIBS += -lgroupsock
LIBS += -lUsageEnvironment
LIBS += -lBasicUsageEnvironment
###
LIBS += -lpluginrtsp4
LIBS += -lpluginpcm
###
LIBS += -lomfapi
LIBS += -lomfapicxx
LIBS += -lomfapistreaming
LIBS += -lpluginapistreaming
###
LIBS += -lshm
LIBS += -lpluginshm
LIBS += -lipc
LIBS += -lpluginipc
###
LIBS += -lpluginbase
LIBS += -lfwcore
LIBS += -lfwbase
LIBS += -lfwporting
###
LIBS += -ldl
LIBS += -ldbglinux
###
INCS +=
###
include ../makefile.tmpl

