ALL =
ALL+=omfZonesSet_
###
CFLAGS +=
CXXFLAGS +=
###
INCS += -I.
###
LIBS += -lomfapi
LIBS += -lomfapicxx
###
LIBS += -lpluginshmbase
###
LIBS += -lfwbase
LIBS += -lfwporting
###
LIBS += -ldl
LIBS += -ldbglinux
###
OBJS +=
###
include ../makefile.tmpl
	