ALL =
ALL+=omfAacPlayer_
###
CFLAGS +=
CXXFLAGS +=
###
INCS += -I.
###
LIBS += -lpluginiofile
#LIBS += -lpluginwav
#LIBS += -lpluginmp4
#LIBS += -lpluginav
LIBS += -lpluginpcm
###
LIBS += -lomfapi
LIBS += -lomfapicxx
LIBS += -lomfapistreaming
LIBS += -lpluginapistreaming
###
LIBS += -lshm
LIBS += -lpluginshm
LIBS += -lipc
LIBS += -lpluginipc
###
LIBS += -lpluginbase
LIBS += -lfwcore
LIBS += -lfwbase
LIBS += -lfwporting
###
LIBS += -ldl
LIBS += -ldbglinux
###
OBJS +=
###
include ../makefile.tmpl
	