ALL =
ALL+=omfAacPlayer_
###
CFLAGS +=
CXXFLAGS +=
###
INCS += -I.
###
LIBS += -lpluginiofile
LIBS += -lpluginpcm
###
LIBS += -lomfapi
LIBS += -lomfapicxx
LIBS += -lomfapistreaming
LIBS += -lpluginapistreaming
###
LIBS += -lpluginshmbase
LIBS += -lpluginshm
###
LIBS += -laac
LIBS += -lpluginaac
###
LIBS += -lpluginbase
LIBS += -lfwcore
LIBS += -lfwbase
LIBS += -lfwporting
###
LIBS += -ldl
LIBS += -ldbglinux
###
OBJS +=
###
include ../makefile.tmpl
	