#ifndef __REMOTE_PUSH_ERRNO_H__
#define __REMOTE_PUSH_ERRNO_H__

typedef enum  {
	REMOTE_PUSH_ERRNO_SUCCESS = 0,
	REMOTE_PUSH_ERRNO_PARAM,
	REMOTE_PUSH_ERRNO_NOMEM,
	REMOTE_PUSH_ERRNO_EMPTY,
	REMOTE_PUSH_ERRNO_CREATE,
	REMOTE_PUSH_ERRNO_SEND,
	REMOTE_PUSH_ERRNO_RECEIVE,
	REMOTE_PUSH_ERRNO_OTHERS,
}remotePushErrno_e;






#endif