ALL =
ALL+=omfHlsMuxer_
##
INCS +=
###
LIBS += -lpluginhls
LIBS += -lpluginiofile
LIBS += -lpluginwav
LIBS += -lpluginpcm
###
LIBS += -lomfapi
LIBS += -lomfapicxx
LIBS += -lomfapistreaming
LIBS += -lpluginapistreaming
LIBS += -lpluginav
###
LIBS += -lpluginshmbase
LIBS += -lpluginshm
###
LIBS += -lpluginbase
LIBS += -lfwcore
LIBS += -lfwbase
LIBS += -lfwporting
###
LIBS += -ldl
LIBS += -ldbglinux
###
OBJS +=
###
include ../makefile.tmpl
	